-- XÓA CÁC BẢNG
DROP TABLE IF EXISTS ETL_LOG;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS SQL_COMMANDS;
DROP TABLE IF EXISTS PROCESS;
DROP TABLE IF EXISTS PROCESS_LOG;

-- 1. 
CREATE TABLE CONFIG (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
 	TEN VARCHAR(255) NOT NULL,
 	URL TEXT,
 	DATE_CONFIG DATE,
 	TEN_SP TEXT,
 	LINK TEXT,
 	LINK_ANH TEXT,
 	GIA_CU TEXT,
 	GIA_MOI TEXT,
 	KICH_THUOC_MAN_HINH TEXT,
 	RAM TEXT,
 	BO_NHO TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO CONFIG (
 	TEN, URL, DATE_CONFIG, TEN_SP, LINK, LINK_ANH, GIA_CU, GIA_MOI,
 	KICH_THUOC_MAN_HINH, RAM, BO_NHO)
VALUES (
 	'CELLPHONES',
 	'https://cellphones.com.vn/mobile.html',
 	CURDATE(),
 	'.product__name h3',
 	'a.product__link',
 	'.product__image img',
 	'.product__price--through',
 	'.product__price--show', 
 	'.product__badge p', 
 	'.product__badge p', 
 	'.product__badge p'
), (
 	'TGDD',
 	'https://www.thegioididong.com/dtdd',
 	CURDATE(),
 	'h3',
 	'a.main-contain',
 	'.item-img img',
 	'.price-old',
 	'strong.price',
 	'.item-compare span',
 	'.prods-group li.act',
 	'.prods-group li.act'
);

-- 2. 
CREATE TABLE ETL_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_CONFIG INT, 
	RUN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	STATUS VARCHAR(50),
	MESSAGE TEXT,
	CONSTRAINT FK_LOG_CONFIG FOREIGN KEY (ID_CONFIG) REFERENCES CONFIG (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Các lệnh chỉnh sửa.
ALTER TABLE config
ADD COLUMN PRODUCT_CONTAINER TEXT AFTER URL;

UPDATE config
SET PRODUCT_CONTAINER = 'div.product-info-container.product-item'
WHERE TEN = 'CELLPHONES';

UPDATE config
SET PRODUCT_CONTAINER = 'li.item'
WHERE TEN = 'TGDD';

ALTER TABLE config RENAME COLUMN TEN_SP TO THE_TEN_SP;
ALTER TABLE config RENAME COLUMN LINK TO THE_LINK;
ALTER TABLE config RENAME COLUMN LINK_ANH TO THE_LINK_ANH;
ALTER TABLE config RENAME COLUMN GIA_CU TO THE_GIA_CU;
ALTER TABLE config RENAME COLUMN GIA_MOI TO THE_GIA_MOI;
ALTER TABLE config RENAME COLUMN KICH_THUOC_MAN_HINH TO THE_KICH_THUOC_MAN_HINH;
ALTER TABLE config RENAME COLUMN RAM TO THE_RAM;
ALTER TABLE config RENAME COLUMN BO_NHO TO THE_BO_NHO;
ALTER TABLE config ADD COLUMN THE_PRODUCT_CONTAINER TEXT AFTER URL;

UPDATE config
SET 
    THE_PRODUCT_CONTAINER = 'div.product-info-container.product-item',
    THE_BTN_SHOW_MORE = 'a.btn-show-more'
WHERE TEN = 'CELLPHONES';

UPDATE config
SET 
    THE_PRODUCT_CONTAINER = 'li.item',
    THE_BTN_SHOW_MORE = 'strong.see-more-btn'
WHERE TEN = 'TGDD';

ALTER TABLE etl_log
ADD COLUMN ROWS_AFFECTED INT NULL DEFAULT NULL AFTER MESSAGE;


-- ----------------------------------------------------------------------------------
-- 3
CREATE TABLE SQL_COMMANDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMMAND_NAME VARCHAR(100) NOT NULL UNIQUE,
    SQL_QUERY LONGTEXT NOT NULL,
    DESCRIPTION VARCHAR(255)
);

-- Lệnh 1
DELETE FROM SQL_COMMANDS WHERE COMMAND_NAME = 'SP_ETL_PRODUCT_SCD_CREATE_FIXED';

INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) VALUES
('SP_ETL_PRODUCT_SCD_CREATE_FIXED',
'
DELIMITER $$
CREATE PROCEDURE SP_ETL_Product_SCD (
IN p_ProcessLogID INT
)
BEGIN
DECLARE RowsInput INT DEFAULT 0;
DECLARE RowsCleaned INT DEFAULT 0;
DECLARE RowsInserted INT DEFAULT 0;
DECLARE RowsUpdated INT DEFAULT 0;
CREATE TEMPORARY TABLE IF NOT EXISTS _ExpiredKeys (
TEN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
LINK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
);
DROP TEMPORARY TABLE IF EXISTS CLEANED_DATA;
CREATE TEMPORARY TABLE CLEANED_DATA (
ID INT,
TEN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
LINK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
LINK_ANH VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
GIA_CU DECIMAL(18,2),
GIA_MOI DECIMAL(18,2),
KICH_THUOC_MAN_HINH DECIMAL(4,2),
RAM INT,
BO_NHO INT,
GIAM_GIA_SMEMBER DECIMAL(18,2),
GIAM_GIA_SSTUDENT DECIMAL(18,2),
GIAM_GIA_PHAN_TRAM FLOAT,
COUPON TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
QUA_TANG TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
DANH_GIA FLOAT,
DA_BAN INT
);

SELECT COUNT(*) INTO RowsInput
FROM PRODUCTS_GENERAL;

INSERT INTO CLEANED_DATA
SELECT 
G.ID, 
IFNULL(NULLIF(G.TEN, ''''), ''Unknown''),
IFNULL(NULLIF(G.LINK, ''''), ''Unknown''),
IFNULL(NULLIF(G.LINK_ANH, ''''), ''Unknown''),
IF(G.GIA_CU IS NULL OR G.GIA_CU = '''' OR G.GIA_CU = ''-1'', -1, 
COALESCE(CAST(REPLACE(REPLACE(REPLACE(REPLACE(G.GIA_CU, ''.'', ''''), '','', ''''), ''₫'', ''''), ''đ'', '''') AS DECIMAL(18,2)), -1)
),
IF(G.GIA_MOI IS NULL OR G.GIA_MOI = '''' OR G.GIA_MOI = ''-1'', -1,
COALESCE(CAST(REPLACE(REPLACE(REPLACE(REPLACE(G.GIA_MOI, ''.'', ''''), '','', ''''), ''₫'', ''''), ''đ'', '''') AS DECIMAL(18,2)), -1)
),
IF(G.KICH_THUOC_MAN_HINH IS NULL OR G.KICH_THUOC_MAN_HINH = '''', -1, 
COALESCE(CAST(REGEXP_SUBSTR(G.KICH_THUOC_MAN_HINH, ''[0-9]*\\.?[0-9]+'') AS DECIMAL(4,2)), -1)
),
IF(G.RAM IS NULL OR G.RAM = '''', -1, 
COALESCE(CAST(REPLACE(REPLACE(G.RAM, ''GB'', ''''), '' '', '''') AS SIGNED), -1)
),
IF(G.BO_NHO IS NULL OR G.BO_NHO = '''', -1,
COALESCE(CAST(REPLACE(REPLACE(G.BO_NHO, ''GB'', ''''), '' '', '''') AS SIGNED), -1)
),
IF(G.GIAM_GIA_SMEMBER IS NULL OR G.GIAM_GIA_SMEMBER = '''', -1, 
COALESCE( CAST(REGEXP_SUBSTR(G.GIAM_GIA_SMEMBER, ''[0-9]{1,3}(?:\\.[0-9]{3})*[0-9]{3}'') AS DECIMAL(18,2)), -1)
),
IF(G.GIAM_GIA_SSTUDENT IS NULL OR G.GIAM_GIA_SSTUDENT = '''', -1,
COALESCE(CAST(REPLACE(REPLACE(REPLACE(G.GIAM_GIA_SSTUDENT, ''.'', ''''), '','', ''''), ''đ'', '''') AS DECIMAL(18,2)), -1)
),
IF(G.GIAM_GIA_PHAN_TRAM IS NULL OR G.GIAM_GIA_PHAN_TRAM = '''', -1,
COALESCE( CAST(REPLACE(REPLACE(G.GIAM_GIA_PHAN_TRAM, ''%'', ''''), ''-'', '''') AS FLOAT) / 100.0, -1)
),
IFNULL(NULLIF(G.COUPON, ''''), ''Unknown''),
IFNULL(NULLIF(G.QUA_TANG, ''''), ''Unknown''),
IF(G.DANH_GIA IS NULL OR G.DANH_GIA = '''', -1,
COALESCE(CAST(G.DANH_GIA AS FLOAT), -1)
),
IF(G.DA_BAN IS NULL OR G.DA_BAN = '''' OR NOT (G.DA_BAN REGEXP ''[0-9]''), -1,
COALESCE(CAST(REGEXP_SUBSTR(G.DA_BAN, ''[0-9]+'') AS SIGNED), -1)
)
FROM PRODUCTS_GENERAL G
WHERE LENGTH(IFNULL(G.TEN,'''')) + LENGTH(IFNULL(G.LINK,'''')) + LENGTH(IFNULL(G.LINK_ANH,'''')) > 10;

SELECT COUNT(*) INTO RowsCleaned
FROM CLEANED_DATA;

INSERT INTO PRODUCTS_TRANSFORM (
ID, TEN, LINK, LINK_ANH, GIA_CU, GIA_MOI,
KICH_THUOC_MAN_HINH, RAM, BO_NHO,
GIAM_GIA_SMEMBER, GIAM_GIA_SSTUDENT, GIAM_GIA_PHAN_TRAM,
COUPON, QUA_TANG, DANH_GIA, DA_BAN, CREATED_AT, UPDATED_AT, EXPIRED_AT)
SELECT 
s.ID, s.TEN, s.LINK, s.LINK_ANH, s.GIA_CU, s.GIA_MOI,
s.KICH_THUOC_MAN_HINH, s.RAM, s.BO_NHO,
s.GIAM_GIA_SMEMBER, s.GIAM_GIA_SSTUDENT, s.GIAM_GIA_PHAN_TRAM,
s.COUPON, s.QUA_TANG, s.DANH_GIA, s.DA_BAN,
NOW(), NOW(), ''9999-12-31'' 
FROM CLEANED_DATA s
LEFT JOIN PRODUCTS_TRANSFORM t ON s.TEN = t.TEN AND s.LINK = t.LINK AND t.EXPIRED_AT = ''9999-12-31''
WHERE t.TEN IS NULL;

SET RowsInserted = ROW_COUNT();

TRUNCATE TABLE _ExpiredKeys;
INSERT INTO _ExpiredKeys (TEN, LINK)
SELECT t.TEN, t.LINK
FROM PRODUCTS_TRANSFORM t
INNER JOIN CLEANED_DATA s
ON t.TEN = s.TEN AND t.LINK = s.LINK
AND t.EXPIRED_AT = ''9999-12-31''
WHERE
t.GIA_CU <> s.GIA_CU OR
t.GIA_MOI <> s.GIA_MOI OR
t.KICH_THUOC_MAN_HINH <> s.KICH_THUOC_MAN_HINH OR
t.RAM <> s.RAM OR
t.BO_NHO <> s.BO_NHO OR
t.GIAM_GIA_PHAN_TRAM <> s.GIAM_GIA_PHAN_TRAM;

UPDATE PRODUCTS_TRANSFORM t
INNER JOIN _ExpiredKeys ek ON t.TEN = ek.TEN AND t.LINK = ek.LINK
SET t.EXPIRED_AT = NOW(), t.UPDATED_AT = NOW() -- NOW() thay cho GETDATE()
WHERE t.EXPIRED_AT = ''9999-12-31'';

SET RowsUpdated = ROW_COUNT();

INSERT INTO PRODUCTS_TRANSFORM (
ID, TEN, LINK, LINK_ANH, GIA_CU, GIA_MOI,
KICH_THUOC_MAN_HINH, RAM, BO_NHO,
GIAM_GIA_SMEMBER, GIAM_GIA_SSTUDENT, GIAM_GIA_PHAN_TRAM,
COUPON, QUA_TANG, DANH_GIA, DA_BAN, CREATED_AT, UPDATED_AT, EXPIRED_AT)
SELECT 
s.ID, s.TEN, s.LINK, s.LINK_ANH, s.GIA_CU, s.GIA_MOI,
s.KICH_THUOC_MAN_HINH, s.RAM, s.BO_NHO,
s.GIAM_GIA_SMEMBER, s.GIAM_GIA_SSTUDENT, s.GIAM_GIA_PHAN_TRAM,
s.COUPON, s.QUA_TANG, s.DANH_GIA, s.DA_BAN,
NOW(), NOW(), ''9999-12-31''
FROM CLEANED_DATA s

INNER JOIN _ExpiredKeys ek ON s.TEN = ek.TEN AND s.LINK = ek.LINK;

SET RowsInserted = RowsInserted + ROW_COUNT();
UPDATE db_control.PROCESS_LOG
SET
END_TIME = NOW(),
STATUS = ''Success'',
ROWS_INPUT = RowsInput,
ROWS_CLEANED = RowsCleaned,
ROWS_UPDATED = RowsUpdated,
ROWS_INSERTED = RowsInserted,
MESSAGE = ''Transformation completed successfully''
WHERE ID = p_ProcessLogID;

SELECT
RowsInput AS RowsInput,
RowsCleaned AS RowsCleaned,
RowsUpdated AS RowsUpdated,
RowsInserted AS RowsInserted;

DROP TEMPORARY TABLE IF EXISTS CLEANED_DATA;
DROP TEMPORARY TABLE IF EXISTS _ExpiredKeys;
END$$
DELIMITER;
', 'Tạo Stored Procedure thực hiện ETL, làm sạch dữ liệu và áp dụng SCD Type 2 cho bảng sản phẩm.')
-- Lệnh 2
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) VALUES
('SP_ETL_PRODUCT_SCD_EXEC', 'CALL SP_ETL_Product_SCD(?)', 'Thực thi Stored Procedure ETL và truyền ID của PROCESS_LOG.')

-- 4
CREATE TABLE PROCESS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEN_PROCESS VARCHAR(255) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    TARGET_TABLE VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

INSERT INTO PROCESS (TEN_PROCESS, SOURCE_TABLE, TARGET_TABLE, IS_ACTIVE)
VALUES ('Product_Full_SCD','PRODUCTS_GENERAL', 'PRODUCTS_TRANSFORM', TRUE);

-- 5
CREATE TABLE PROCESS_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PROCESS INT,
	START_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	END_TIME DATETIME,
	STATUS VARCHAR(50),
	MESSAGE TEXT,
	CONSTRAINT FK_PROCESSLOG_PROCESS FOREIGN KEY (ID_PROCESS) REFERENCES PROCESS (ID)
);

