-- XÓA CÁC BẢNG
DROP TABLE IF EXISTS ETL_LOG;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS SQL_COMMANDS;
DROP TABLE IF EXISTS PROCESS;
DROP TABLE IF EXISTS PROCESS_LOG;

-- 1. 
CREATE TABLE CONFIG (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
 	TEN VARCHAR(255) NOT NULL,
 	URL TEXT,
 	DATE_CONFIG DATE,
 	TEN_SP TEXT,
 	LINK TEXT,
 	LINK_ANH TEXT,
 	GIA_CU TEXT,
 	GIA_MOI TEXT,
 	KICH_THUOC_MAN_HINH TEXT,
 	RAM TEXT,
 	BO_NHO TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO CONFIG (
 	TEN, URL, DATE_CONFIG, TEN_SP, LINK, LINK_ANH, GIA_CU, GIA_MOI,
 	KICH_THUOC_MAN_HINH, RAM, BO_NHO)
VALUES (
 	'CELLPHONES',
 	'https://cellphones.com.vn/mobile.html',
 	CURDATE(),
 	'.product__name h3',
 	'a.product__link',
 	'.product__image img',
 	'.product__price--through',
 	'.product__price--show', 
 	'.product__badge p', 
 	'.product__badge p', 
 	'.product__badge p'
), (
 	'TGDD',
 	'https://www.thegioididong.com/dtdd',
 	CURDATE(),
 	'h3',
 	'a.main-contain',
 	'.item-img img',
 	'.price-old',
 	'strong.price',
 	'.item-compare span',
 	'.prods-group li.act',
 	'.prods-group li.act'
);

-- 2. 
CREATE TABLE ETL_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_CONFIG INT, 
	RUN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	STATUS VARCHAR(50),
	MESSAGE TEXT,
	CONSTRAINT FK_LOG_CONFIG FOREIGN KEY (ID_CONFIG) REFERENCES CONFIG (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Các lệnh chỉnh sửa.
ALTER TABLE config
ADD COLUMN PRODUCT_CONTAINER TEXT AFTER URL;

UPDATE config
SET PRODUCT_CONTAINER = 'div.product-info-container.product-item'
WHERE TEN = 'CELLPHONES';

UPDATE config
SET PRODUCT_CONTAINER = 'li.item'
WHERE TEN = 'TGDD';

ALTER TABLE config RENAME COLUMN TEN_SP TO THE_TEN_SP;
ALTER TABLE config RENAME COLUMN LINK TO THE_LINK;
ALTER TABLE config RENAME COLUMN LINK_ANH TO THE_LINK_ANH;
ALTER TABLE config RENAME COLUMN GIA_CU TO THE_GIA_CU;
ALTER TABLE config RENAME COLUMN GIA_MOI TO THE_GIA_MOI;
ALTER TABLE config RENAME COLUMN KICH_THUOC_MAN_HINH TO THE_KICH_THUOC_MAN_HINH;
ALTER TABLE config RENAME COLUMN RAM TO THE_RAM;
ALTER TABLE config RENAME COLUMN BO_NHO TO THE_BO_NHO;
ALTER TABLE config ADD COLUMN THE_PRODUCT_CONTAINER TEXT AFTER URL;

UPDATE config
SET 
    THE_PRODUCT_CONTAINER = 'div.product-info-container.product-item',
    THE_BTN_SHOW_MORE = 'a.btn-show-more'
WHERE TEN = 'CELLPHONES';

UPDATE config
SET 
    THE_PRODUCT_CONTAINER = 'li.item',
    THE_BTN_SHOW_MORE = 'strong.see-more-btn'
WHERE TEN = 'TGDD';

ALTER TABLE etl_log
ADD COLUMN ROWS_AFFECTED INT NULL DEFAULT NULL AFTER MESSAGE;


-- ----------------------------------------------------------------------------------

-- 3
CREATE TABLE PROCESS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEN_PROCESS VARCHAR(255) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    TARGET_TABLE VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

INSERT INTO PROCESS (TEN_PROCESS, SOURCE_TABLE, TARGET_TABLE, IS_ACTIVE)
VALUES ('Transform_Process','PRODUCTS_GENERAL', 'PRODUCTS_TRANSFORM', TRUE);

-- 4
CREATE TABLE PROCESS_LOG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PROCESS INT,
	START_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	END_TIME DATETIME,
	STATUS VARCHAR(50),
	MESSAGE TEXT,
	CONSTRAINT FK_PROCESSLOG_PROCESS FOREIGN KEY (ID_PROCESS) REFERENCES PROCESS (ID)
);

-- 5
CREATE TABLE SQL_COMMANDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMMAND_NAME VARCHAR(100) NOT NULL UNIQUE,
    SQL_QUERY LONGTEXT NOT NULL,
    DESCRIPTION VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Lệnh 1
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) 
VALUES ('SP_ETL_CLEAN_DATA', 
'DELIMITER $$
CREATE PROCEDURE SP_ETL_Clean_Data ()
BEGIN
TRUNCATE TABLE PRODUCTS_TRANSFORM;
INSERT INTO PRODUCTS_TRANSFORM (
ID, TEN, LINK, LINK_ANH, GIA_CU, GIA_MOI,
KICH_THUOC_MAN_HINH, RAM, BO_NHO, SK_DATE, NGAY
)
WITH TransformedSourceData AS (
SELECT
G.ID,
IFNULL(NULLIF(G.TEN, ''''), ''Unknown'') AS TEN,
IFNULL(NULLIF(G.LINK, ''''), ''Unknown'') AS LINK,
IFNULL(NULLIF(G.LINK_ANH, ''''), ''Unknown'') AS LINK_ANH,
IF(G.GIA_CU IS NULL OR G.GIA_CU = '''' OR G.GIA_CU = ''-1'', -1,
COALESCE(CAST(REPLACE(REPLACE(REPLACE(REPLACE(G.GIA_CU, ''.'', ''''), '','', ''''), ''₫'', ''''), ''đ'', '''') AS DECIMAL(18,2)), -1)
) AS GIA_CU,
IF(G.GIA_MOI IS NULL OR G.GIA_MOI = '''' OR G.GIA_MOI = ''-1'', -1,
COALESCE(CAST(REPLACE(REPLACE(REPLACE(REPLACE(G.GIA_MOI, ''.'', ''''), '','', ''''), ''₫'', ''''), ''đ'', '''') AS DECIMAL(18,2)), -1)
) AS GIA_MOI,
IF(G.KICH_THUOC_MAN_HINH IS NULL OR G.KICH_THUOC_MAN_HINH = '''', -1,
COALESCE(CAST(REGEXP_SUBSTR(G.KICH_THUOC_MAN_HINH, ''[0-9]*\\.?[0-9]+'') AS DECIMAL(4,2)), -1)
) AS KICH_THUOC_MAN_HINH,
IF(G.RAM IS NULL OR G.RAM = '''', -1,
COALESCE(CAST(REPLACE(REPLACE(G.RAM, ''GB'', ''''), '' '', '''') AS SIGNED), -1)) AS RAM,
IF(G.BO_NHO IS NULL OR G.BO_NHO = '''', -1,
COALESCE(CAST(REPLACE(REPLACE(G.BO_NHO, ''GB'', ''''), '' '', '''') AS SIGNED), -1)
) AS BO_NHO,
IFNULL(dd.DATE_SK, 0) AS SK_DATE,
G.NGAY
FROM PRODUCTS_GENERAL G
LEFT JOIN db_staging.DIM_DATE dd ON DATE(G.NGAY) = dd.FULL_DATE
WHERE LENGTH(IFNULL(G.TEN,'''')) + LENGTH(IFNULL(G.LINK,'''')) + LENGTH(IFNULL(G.LINK_ANH,'''')) > 10
)
SELECT
s.ID, s.TEN, s.LINK, s.LINK_ANH, s.GIA_CU, s.GIA_MOI,
s.KICH_THUOC_MAN_HINH, s.RAM, s.BO_NHO, s.SK_DATE, s.NGAY
FROM TransformedSourceData s;
END$$
DELIMITER ;',
'Làm sạch dữ liệu từ PRODUCTS_GENERAL và nạp toàn bộ vào PRODUCTS_TRANSFORM.');
-- Lệnh 2
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) 
VALUES ('SP_ETL_SCD_UPDATE_PRODUCT', 
'DELIMITER $$
CREATE PROCEDURE SP_ETL_SCD_Update_Product (
OUT p_RowsInput INT,
OUT p_RowsInserted INT,
OUT p_RowsUpdated INT
)
BEGIN
DECLARE CurrentRowsInserted INT DEFAULT 0;

SELECT COUNT(*) INTO p_RowsInput
FROM PRODUCTS_TRANSFORM;

INSERT INTO PRODUCTS_EXPIRED (
ID, TEN, LINK, LINK_ANH, GIA_CU, GIA_MOI,
KICH_THUOC_MAN_HINH, RAM, BO_NHO, SK_DATE, NGAY,
CREATED_AT, UPDATED_AT, EXPIRED_AT
)
SELECT
s.ID, s.TEN, s.LINK, s.LINK_ANH, s.GIA_CU, s.GIA_MOI,
s.KICH_THUOC_MAN_HINH, s.RAM, s.BO_NHO, s.SK_DATE, s.NGAY,
NOW(), NOW(), ''9999-12-31''
FROM PRODUCTS_TRANSFORM s
LEFT JOIN PRODUCTS_EXPIRED t
ON s.TEN = t.TEN
AND t.EXPIRED_AT = ''9999-12-31''
WHERE t.TEN IS NULL;

SET CurrentRowsInserted = ROW_COUNT();

TRUNCATE TABLE db_staging.EXPIRED_KEYS; 
INSERT INTO db_staging.EXPIRED_KEYS (TEN, LINK)
SELECT t.TEN, t.LINK
FROM PRODUCTS_EXPIRED t
JOIN PRODUCTS_TRANSFORM s
ON t.TEN = s.TEN
AND t.EXPIRED_AT = ''9999-12-31''
WHERE
t.GIA_CU <> s.GIA_CU OR
t.GIA_MOI <> s.GIA_MOI OR
t.KICH_THUOC_MAN_HINH <> s.KICH_THUOC_MAN_HINH OR
t.RAM <> s.RAM OR
t.BO_NHO <> s.BO_NHO;

UPDATE PRODUCTS_EXPIRED t
INNER JOIN db_staging.EXPIRED_KEYS ek ON t.TEN = ek.TEN AND t.LINK = ek.LINK
SET t.EXPIRED_AT = NOW(), t.UPDATED_AT = NOW()
WHERE t.EXPIRED_AT = ''9999-12-31'';

SET p_RowsUpdated = ROW_COUNT();

INSERT INTO PRODUCTS_EXPIRED (
ID, TEN, LINK, LINK_ANH, GIA_CU, GIA_MOI,
KICH_THUOC_MAN_HINH, RAM, BO_NHO, SK_DATE, NGAY,
CREATED_AT, UPDATED_AT, EXPIRED_AT
)
SELECT
s.ID, s.TEN, s.LINK, s.LINK_ANH, s.GIA_CU, s.GIA_MOI,
s.KICH_THUOC_MAN_HINH, s.RAM, s.BO_NHO, s.SK_DATE, s.NGAY,
NOW(), NOW(), ''9999-12-31''
FROM PRODUCTS_TRANSFORM s
JOIN db_staging.EXPIRED_KEYS ek ON s.TEN = ek.TEN AND s.LINK = ek.LINK;

SET p_RowsInserted = CurrentRowsInserted + ROW_COUNT();
END$$
DELIMITER ;',
'Thực hiện logic Slowly Changing Dimension Type 2 (SCD Type 2) cho bảng sản phẩm.');

-- Lệnh 3
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) 
VALUES ('SP_ETL_UPDATE_LOG_STATUS', 
'DELIMITER $$
CREATE PROCEDURE SP_ETL_Update_Log_Status (
IN p_ProcessLogID INT,
IN p_RowsInput INT,
IN p_RowsInserted INT,
IN p_RowsUpdated INT,
IN p_Status VARCHAR(50)
)
BEGIN
DECLARE log_message TEXT;

SET log_message = CONCAT(
''SCD Type 2 completed successfully. '',
''Rows Processed: '', p_RowsInput, ''. '',
''New Rows Inserted: '', p_RowsInserted, ''. '',
''Old Rows Expired (Updated): '', p_RowsUpdated, ''.''
);

UPDATE db_control.PROCESS_LOG
SET
END_TIME = NOW(),
STATUS = p_Status,
MESSAGE = log_message
WHERE ID = p_ProcessLogID;
END$$
DELIMITER ;', 
'Cập nhật log vào PROCESS_LOG.');

-- Lệnh 4
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION) 
VALUES ('SP_ETL_PRODUCT_SCD_EXEC', 'CALL SP_ETL_Product_SCD(?)', 'Thực thi Stored Procedure ETL và truyền ID của PROCESS_LOG.');

-- Lệnh 5
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION)
VALUES ('COUNT_RUNNING_PROCESS_LOG',
    'SELECT COUNT(*) AS running_count FROM PROCESS_LOG WHERE STATUS = ''Running''',
    'Đếm số lượng tiến trình đang ở trạng thái Running trong bảng PROCESS_LOG.');

-- Lệnh 6
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION)
VALUES ('COUNT_RUNNING_ETL_LOG',
    'SELECT COUNT(*) AS running_count FROM ETL_LOG WHERE STATUS = ''Running''',
    'Đếm số lượng tiến trình đang ở trạng thái Running trong bảng ETL_LOG.');

-- Lệnh 7
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION)
VALUES (
    'SELECT_PROCESS_ID',
    'SELECT ID FROM PROCESS WHERE TEN_PROCESS = %s',
    'Lấy ID của tiến trình từ bảng PROCESS dựa trên tên (sử dụng tham số %s).');

-- Lệnh 8
INSERT INTO SQL_COMMANDS (COMMAND_NAME, SQL_QUERY, DESCRIPTION)
VALUES (
    'INSERT_PROCESS_LOG_RUNNING',
    'INSERT INTO PROCESS_LOG (ID_PROCESS, STATUS, MESSAGE) VALUES (%s, %s, ''Process started'')',
    'Chèn một dòng mới vào PROCESS_LOG, thiết lập trạng thái Running và thông báo bắt đầu.');

-- Xóa bảng etl_log, tạo bảng crawl log mới --
DROP TABLE IF EXISTS etl_log;

CREATE TABLE crawl_log (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CONFIG INT, 
    RUN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20),
    FILE_PATH VARCHAR(500), 
    SITE_NAME VARCHAR(100), 
    ROWS_AFFECTED INT DEFAULT 0,
    ERROR_MESSAGE TEXT,
    
    CONSTRAINT FK_CRAWL_CONFIG FOREIGN KEY (ID_CONFIG) REFERENCES config (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


