CREATE TABLE PRODUCTS_GENERAL (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
 	TEN TEXT,
 	LINK TEXT,
 	LINK_ANH TEXT,
 	GIA_CU TEXT,
 	GIA_MOI TEXT,
 	KICH_THUOC_MAN_HINH TEXT,
 	RAM TEXT,
 	BO_NHO TEXT,
 	GIAM_GIA_SMEMBER TEXT,
 	GIAM_GIA_SSTUDENT TEXT,
 	GIAM_GIA_PHAN_TRAM TEXT, 	 
 	COUPON TEXT,
 	QUA_TANG TEXT, 			 
	DANH_GIA TEXT,
 	DA_BAN TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE PRODUCTS_TRANSFORM (
	ID_SR INT AUTO_INCREMENT PRIMARY KEY, 
 	ID INT, 
 	TEN VARCHAR(255),
 	LINK VARCHAR(500), 
 	LINK_ANH VARCHAR(500), 
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT,
 	GIAM_GIA_SMEMBER DECIMAL(18,2),
 	GIAM_GIA_SSTUDENT DECIMAL(18,2),
 	GIAM_GIA_PHAN_TRAM FLOAT, 	 
 	COUPON TEXT,
 	QUA_TANG TEXT, 			 
	DANH_GIA FLOAT,
 	DA_BAN INT,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
 	UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	EXPIRED_AT DATETIME DEFAULT '9999-12-31'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE PRODUCTS_GENERAL
ADD COLUMN ID_CONFIG INT NULL;

ALTER TABLE PRODUCTS_TRANSFORM
ADD COLUMN ID_CONFIG INT NULL;
