-- XÓA CÁC BẢNG
DROP TABLE IF EXISTS PRODUCTS_GENERAL;
DROP TABLE IF EXISTS PRODUCTS_TRANSFORM;
DROP TABLE IF EXISTS PRODUCTS_EXPIRED;
-- 1
CREATE TABLE PRODUCTS_GENERAL (
ID INT AUTO_INCREMENT PRIMARY KEY,
TEN TEXT,
LINK TEXT,
LINK_ANH TEXT,
GIA_CU TEXT,
GIA_MOI TEXT,
KICH_THUOC_MAN_HINH TEXT,
RAM TEXT,
BO_NHO TEXT,
NGAY DATETIME
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
-- 2
CREATE TABLE PRODUCTS_TRANSFORM (
	ID_SR INT AUTO_INCREMENT PRIMARY KEY, 
 	ID INT, 
 	TEN VARCHAR(255),
 	LINK VARCHAR(500), 
 	LINK_ANH VARCHAR(500), 
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT,
 	SK_DATE INT,
  NGAY DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
-- 3
CREATE TABLE PRODUCTS_EXPIRED (
	ID_SR INT AUTO_INCREMENT PRIMARY KEY, 
 	ID INT, 
 	TEN VARCHAR(255),
 	LINK VARCHAR(500), 
 	LINK_ANH VARCHAR(500), 
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT,
 	SK_DATE INT,
  NGAY DATETIME,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
 	UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	EXPIRED_AT DATETIME DEFAULT '9999-12-31'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Các lệnh chỉnh sửa
ALTER TABLE PRODUCTS_GENERAL
ADD COLUMN ID_CONFIG INT NULL;

ALTER TABLE PRODUCTS_TRANSFORM
ADD COLUMN ID_CONFIG INT NULL;
-- Thay đổi Collation
ALTER TABLE PRODUCTS_GENERAL
MODIFY COLUMN TEN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE PRODUCTS_GENERAL
MODIFY COLUMN LINK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE PRODUCTS_TRANSFORM
MODIFY COLUMN TEN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE PRODUCTS_TRANSFORM
MODIFY COLUMN LINK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


