-- XÓA CÁC BẢNG
DROP TABLE IF EXISTS PRODUCTS_GENERAL;
DROP TABLE IF EXISTS PRODUCTS_TRANSFORM;
DROP TABLE IF EXISTS PRODUCTS_EXPIRED;
DROP TABLE IF EXISTS EXPIRED_KEYS;
DROP TABLE IF EXISTS DIM_DATE;
-- 1
CREATE TABLE PRODUCTS_GENERAL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TEN TEXT,
  LINK TEXT,
  LINK_ANH TEXT,
  GIA_CU TEXT,
  GIA_MOI TEXT,
  KICH_THUOC_MAN_HINH TEXT,
  RAM TEXT,
  BO_NHO TEXT,
  NGAY DATETIME
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- 2
CREATE TABLE PRODUCTS_TRANSFORM (
	ID_SR INT AUTO_INCREMENT PRIMARY KEY, 
 	ID INT, 
 	TEN VARCHAR(255),
 	LINK VARCHAR(500), 
 	LINK_ANH VARCHAR(500), 
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT,
 	SK_DATE INT,
  NGAY DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- 3
CREATE TABLE PRODUCTS_EXPIRED (
	ID_SR INT AUTO_INCREMENT PRIMARY KEY, 
 	ID INT, 
 	TEN VARCHAR(255),
 	LINK VARCHAR(500), 
 	LINK_ANH VARCHAR(500), 
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT,
 	SK_DATE INT,
  NGAY DATETIME,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
 	UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	EXPIRED_AT DATETIME DEFAULT '9999-12-31'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- 4
CREATE TABLE EXPIRED_KEYS (
    TEN VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    LINK VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    PRIMARY KEY (TEN, LINK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- 5
CREATE TABLE DIM_DATE (
 	DATE_SK INT AUTO_INCREMENT PRIMARY KEY,
 	FULL_DATE DATE NOT NULL,
	INT_DAY INT NOT NULL,
 	INT_MONTH INT NOT NULL,
 	DAY_OF_WEEK VARCHAR(20) NOT NULL,
 	CALENDAR_MONTH VARCHAR(20) NOT NULL,
 	CALENDAR_YEAR INT NOT NULL,
	CALENDAR_YEAR_MONTH VARCHAR(20) NOT NULL,
 	DATE_OF_MONTH INT NOT NULL,
 	DAY_OF_YEAR INT NOT NULL,
	SUN_WEEK_OF_YEAR INT NOT NULL,
	SUN_YEAR_WEEK VARCHAR(20) NOT NULL,
	SUN_WEEK DATE NOT NULL,
	MON_WEEK_OF_YEAR INT NOT NULL,
	MON_YEAR_WEEK VARCHAR(20) NOT NULL,
	MON_WEEK DATE NOT NULL,
	`QUARTER` VARCHAR(20) NOT NULL, 
 	QUARTER_OF_YEAR DATE NOT NULL,
 	HOLIDAY VARCHAR(25) NOT NULL,
 	DAY_TYPE VARCHAR(20) NOT NULL,
    UNIQUE KEY UK_FULL_DATE (FULL_DATE) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Các lệnh chỉnh sửa
ALTER TABLE PRODUCTS_GENERAL
ADD COLUMN ID_CONFIG INT NULL;

ALTER TABLE PRODUCTS_TRANSFORM
ADD COLUMN ID_CONFIG INT NULL;

INSERT IGNORE INTO db_staging.DIM_DATE (FULL_DATE, INT_DAY, INT_MONTH, DAY_OF_WEEK,CALENDAR_MONTH,CALENDAR_YEAR,CALENDAR_YEAR_MONTH,DATE_OF_MONTH,DAY_OF_YEAR, SUN_WEEK_OF_YEAR,SUN_YEAR_WEEK,SUN_WEEK,MON_WEEK_OF_YEAR,MON_YEAR_WEEK,MON_WEEK,`QUARTER`,QUARTER_OF_YEAR,HOLIDAY,DAY_TYPE)
SELECT T1.FULL_DATE,T1.INT_DAY,T1.INT_MONTH,T1.DAY_OF_WEEK,T1.CALENDAR_MONTH,T1.CALENDAR_YEAR,T1.CALENDAR_YEAR_MONTH,T1.DATE_OF_MONTH,T1.DAY_OF_YEAR,T1.SUN_WEEK_OF_YEAR, T1.SUN_YEAR_WEEK,T1.SUN_WEEK,T1.MON_WEEK_OF_YEAR,T1.MON_YEAR_WEEK,T1.MON_WEEK,T1.`QUARTER`,T1.QUARTER_OF_YEAR,T1.HOLIDAY,T1.DAY_TYPE
FROM db_warehouse.DIM_DATE AS T1;