CREATE TABLE DIM_DATE (
 	DATE_SK INT AUTO_INCREMENT PRIMARY KEY,
 	FULL_DATE DATE NOT NULL,
	INT_DAY INT NOT NULL,
 	INT_MONTH INT NOT NULL,
 	DAY_OF_WEEK VARCHAR(20) NOT NULL,
 	CALENDAR_MONTH VARCHAR(20) NOT NULL,
 	CALENDAR_YEAR INT NOT NULL,
	CALENDAR_YEAR_MONTH VARCHAR(20) NOT NULL,
 	DATE_OF_MONTH INT NOT NULL,
 	DAY_OF_YEAR INT NOT NULL,
	SUN_WEEK_OF_YEAR INT NOT NULL,
	SUN_YEAR_WEEK VARCHAR(20) NOT NULL,
	SUN_WEEK DATE NOT NULL,
	MON_WEEK_OF_YEAR INT NOT NULL,
	MON_YEAR_WEEK VARCHAR(20) NOT NULL,
	MON_WEEK DATE NOT NULL,
	`QUARTER` VARCHAR(20) NOT NULL, 
 	QUARTER_OF_YEAR DATE NOT NULL,
 	HOLIDAY VARCHAR(25) NOT NULL,
 	DAY_TYPE VARCHAR(20) NOT NULL,
    UNIQUE KEY UK_FULL_DATE (FULL_DATE) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE DIM_PROMOTION (
 	PROMOTION_SK INT AUTO_INCREMENT PRIMARY KEY,
 	GIAM_GIA_SMEMBER DECIMAL(18,2),
 	GIAM_GIA_SSTUDENT DECIMAL(18,2),
 	COUPON TEXT,
 	QUA_TANG TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE DIM_BRAND (
 	BRAND_SK INT AUTO_INCREMENT PRIMARY KEY,
 	BRAND_NAME VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE DIM_PRODUCT (
 	PRODUCT_SK INT AUTO_INCREMENT PRIMARY KEY,
 	TEN VARCHAR(255),
 	LINK VARCHAR(500),
 	LINK_ANH VARCHAR(500),
 	KICH_THUOC_MAN_HINH DECIMAL(4,2),
 	RAM INT,
 	BO_NHO INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE FACT_PRODUCT_SALES (
 	FACT_ID INT AUTO_INCREMENT PRIMARY KEY,
 	PRODUCT_SK INT,
 	DATE_SK INT,
 	PROMOTION_SK INT,
 	BRAND_SK INT,
 	GIA_CU DECIMAL(18,2),
 	GIA_MOI DECIMAL(18,2),
 	GIAM_GIA_PHAN_TRAM FLOAT,
 	DA_BAN INT,
 	DANH_GIA FLOAT,
 	CONSTRAINT FK_FACT_PRODUCT FOREIGN KEY (PRODUCT_SK) REFERENCES DIM_PRODUCT(PRODUCT_SK),
 	CONSTRAINT FK_FACT_DATE FOREIGN KEY (DATE_SK) REFERENCES DIM_DATE(DATE_SK),
 	CONSTRAINT FK_FACT_PROMOTION FOREIGN KEY (PROMOTION_SK) REFERENCES DIM_PROMOTION(PROMOTION_SK),
 	CONSTRAINT FK_FACT_BRAND FOREIGN KEY (BRAND_SK) REFERENCES DIM_BRAND(BRAND_SK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE AGGREGATE (
    AGG_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_SK INT,
    PRODUCT_SK INT,
    DATE_SK INT,
    CALENDAR_YEAR INT,
    CALENDAR_MONTH INT,
    
    TOTAL_REVENUE DECIMAL(18,2),
    TOTAL_UNITS_SOLD INT,
    MAX_PRICE DECIMAL(18,2),
    MIN_PRICE DECIMAL(18,2),
	AVG_RATING FLOAT,
    
    CONSTRAINT FK_AGG_BRAND FOREIGN KEY (BRAND_SK) REFERENCES DIM_BRAND(BRAND_SK),
    CONSTRAINT FK_AGG_PRODUCT FOREIGN KEY (PRODUCT_SK) REFERENCES DIM_PRODUCT(PRODUCT_SK),
    CONSTRAINT FK_AGG_DATE FOREIGN KEY (DATE_SK) REFERENCES DIM_DATE(DATE_SK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
